In [1]:
from __future__ import annotations

from datetime import datetime
from dateutil.relativedelta import relativedelta
from pathlib import Path
import re

import pandas as pd

In [3]:
from src.config.config import load_equipment_config, DATA_BASE_DIR
from src.domain.entities.equipment import Equipment, create_equipment
EQUIPMENTS = load_equipment_config(Path("src/config/equipments.yaml"))

In [4]:
from src.databases import OracleCRUD, PostgresCRUD
from ftplib import FTP, all_errors
# from src.databases.postgresql_db import PostgresCRUD

In [ ]:
devices = ["SW2L", "AG14"]
device_query = ",".join([f"'{device}'" for device in devices])
query = f"""
SELECT DISTINCT
    MAT_ID product, MAT_CMF_21 device, MAT_CMF_5 device_name,
    MAT_CMF_6 tech_prod, MAT_CMF_7 tech, MAT_CMF_23 prod_group
FROM IDBMGR.MWIPMATDEF
WHERE FACTORY = 'AFB1'
    AND MAT_CMF_21 IN ({device_query}) 
ORDER BY MAT_CMF_21
"""
df_tech = OracleCRUD.select_query(query)
if df_tech.empty:
    
df_tech["result"] = df_tech.apply(
    lambda row: (
        True
        if row["device_name"] in [None, "", " "]
        else row["device"] in row["product"]
    ),
    axis=1,
)
df_tech.columns = df_tech.columns.str.lower()
df_tech = df_tech[df_tech["result"]].drop(
    ["product", "device_name", "result"], axis=1
)
df_tech = df_tech.drop_duplicates()
df_tech

  device tech_prod  tech prod_group
0   AG14       C05  0.18     BCDMOS
6   SW2L       C05  0.16        LDI

In [4]:
equip = create_equipment(EQUIPMENTS[3])

In [6]:
def parse_edit_time(line: str) -> str:
    """파일 정보 문자 내 최종 수정 일자 파싱"""
    # 연도가 없고 날짜만 있는 경우 : 오늘 월/일보다 뒤에 있을 경우 작년, 오늘 월/일보다 앞에 있을 경우 올해
    pattern_1 = r"(\b[A-Za-z]{3}\s\d{2}\s\d{2}:\d{2}\b)"
    pattern_2 = r"(\b[A-Za-z]{3}\s\s\d{1}\s\d{2}:\d{2}\b)"
    pattern_3 = r"(\b[A-Za-z]{3}\s\d{2}\s\s\d{4}\b)"
    pattern_4 = r"(\b[A-Za-z]{3}\s\s\d{1}\s\s\d{4}\b)"
    pattern_5 = r"(\d+[가-힣]\s\d+[가-힣]\s\d{4}[가-힣])"
    pattern_6 = r"(\d+[가-힣]\s\s\d+[가-힣]\s\d{4}[가-힣])"
    pattern_7 = r"(\d+[가-힣]\s\d+[가-힣]\s\s\d{2}:\d{2}\b)"
    try:
        info = re.findall(pattern_1, line)[0]
        year = datetime.now().year
        edit_time = datetime.strptime(f"{year} {info}", "%Y %b %d %H:%M")
    except:
        try:
            info = re.findall(pattern_2, line)[0]
            year = datetime.now().year
            edit_time = datetime.strptime(f"{year} {info}", "%Y %b  %d %H:%M")
        except:
            try:
                info = re.findall(pattern_3, line)[0]
                edit_time = datetime.strptime(info, "%b %d  %Y")
            except:
                try:
                    info = re.findall(pattern_4, line)[0]
                    edit_time = datetime.strptime(info, "%b  %d  %Y")
                except:
                    try:
                        info = re.findall(pattern_5, line)[0]
                        info = "-".join(
                            [
                                re.match(r"\d+", item).group(0)
                                for item in info.split(" ")
                            ]
                        )
                        edit_time = datetime.strptime(info, "%m-%d-%Y")
                    except:
                        try:
                            info = re.findall(pattern_6, line)[0]
                            info = "-".join(
                                [
                                    re.match(r"\d+", item).group(0)
                                    for item in info.split(" ")
                                    if item is not None and len(item) > 0
                                ]
                            )
                            edit_time = datetime.strptime(info, "%m-%d-%Y")
                        except:
                            try:
                                info = re.findall(pattern_7, line)[0]
                                info = re.sub("[가-힣]", " ", info)
                                edit_time = datetime.strptime(
                                    f"{datetime.now().year} {info}", "%Y %m  %d   %H:%M"
                                )
                            except:
                                print(line)
                                edit_time = datetime.now()
    if edit_time > datetime.now():
        edit_time = edit_time - relativedelta(years=1)
    return edit_time.strftime("%Y-%m-%d %H:%M")


def recipe_filter(file: str) -> bool:
    """Recipe 폴더 필터

    Args:
        file (str): 파일명

    Returns:
        bool: 필터 통과 여부
    """
    # .이나 _로 시작하거나 특정 문자/확장자 로 끝나는 경우 제외
    if file.startswith((".", "_")) or file.endswith(("~", ".inf", ".DAT")):
        return False

    # 언더바(_)로 분할했을 때 정확히 2개여야 하고, 앞부분의 길이가 4여야 함
    parts = file.split("_")
    return len(parts) == 2 and len(parts[0]) == 4

In [18]:
def collect_lines(ftp: FTP) -> List[str]:
    """FTP 폴더 내 파일 정보 수집

    Args:
        ftp (FTP): 접속한 ftp 인스턴스

    Returns:
        List[str]: 폴더/파일 리스트
    """
    lines = []
    def _collect(line):
        lines.append(line)
    ftp.dir(_collect)
    return lines

In [ ]:
def is_recipe(line: str) -> bool:
    """Recipe 폴더 필터

    Args:
        line (str): 파일 정보

    Returns:
        bool: 필터 통과 여부
    """
    info = line.split(" ")
    file_name = info[-1].strip()
    # .이나 _로 시작하거나 특정 문자/확장자 로 끝나는 경우 제외
    if file_name.startswith((".", "_")) or file_name.endswith(("~", ".inf", ".DAT")):
        return False

    # 언더바(_)로 분할했을 때 정확히 2개여야 하고, 앞부분의 길이가 4여야 함
    parts = file_name.split("_")
    return len(parts) == 2 and len(parts[0]) == 4

def transform_recipe_info(
    line: str, equip: Equipment, equip_dir: Path
    ) -> Tuple[str, str, str, str, str, str]:
    """Recipe 정보 추출

    Args:
        line (str): 파일 정보

    Returns:
        Tuple[str, str, str, str, str, str]:
        Recipe Key, Device, Layer, Recipe, Edit Time
    """
    info = line.split(" ")
    file_name = info[-1].strip()
    device, layer = file_name.split("_")
    last_edit_time = parse_edit_time(line)
    recipe_key = f"{equip.name}-{file_name}"
    backup_recipe_dir = equip_dir / file_name
    backup_recipe_path = backup_recipe_dir / "ins.dat"
    return (recipe_key, device, layer, file_name, last_edit_time,backup_recipe_dir, backup_recipe_path)


def is_file_update(equip_db: pd.DataFrame, rcp_key: str, edit_time: datetime, backup_file_path: Path):
    """DB 정보와 파일 최종 수정시간 비교하여 파일 업데이트 상태 최신화"""
    match_info = equip_db[equip_db["recipe_key"] == rcp_key]
    if match_info.empty:
        return True, "new"  # New (신규 Recipe)
    if not backup_file_path.exists():
        return True, "new"
    db_edit_time = match_info.iloc[0]["dt_edit_time"]

    if edit_time > db_edit_time:
        return True, "update"  # Update (수정된 Recipe)
    return False, None

In [41]:
equip_dir = DATA_BASE_DIR / equip.name

In [38]:
df_equip_db = PostgesCRUD.select_query(
    """
	SELECT recipe_key, dt_edit_time, device, layer, recipe, backup_file_path
	FROM dm_recipe_info
	WHERE equip = %s
		AND is_remove=false
	""",
 (equip.name,))

In [ ]:
with FTP(
        timeout=equip.ftp_info.timeout_seconds, encoding=equip.ftp_info.encoding
    ) as ftp:
    ftp.connect(host=equip.ftp_info.host, port=equip.ftp_info.port)
    ftp.login(equip.ftp_info.username, equip.ftp_info.password)
    ftp.cwd(equip.ftp_info.remote_directory)
    lines = collect_lines(ftp)
    recipes = [transform_recipe_info(line, equip) for line in lines if is_recipe(line)]
    for i, (rcp_key, device, layer, recipe, edit_time,
            backup_recipe_dir, backup_recipe_path) in enumerate(recipes):
        is_upsert, file_status = is_file_update(df_equip_db, rcp_key, edit_time, backup_recipe_path)
        if is_upsert:
            backup_recipe_dir.mkdir(parents=True, exists=True)
            ftp_download_tree(ftp, recipe, backup_recipe_dir)
            print(rcp_key, equip.model, equip.name, device, layer, recipe, edit_time)
        if i>5:
            break

SMDI06-A002_1565PAD3 KLA2139 SMDI06 A002 1565PAD3 A002_1565PAD3 2026-09-05 16:10
SMDI06-A003_118062UM KLA2139 SMDI06 A003 118062UM A003_118062UM 2026-09-05 16:10
SMDI06-A003_1400MOPT KLA2139 SMDI06 A003 1400MOPT A003_1400MOPT 2026-09-05 16:10
SMDI06-A003_145062UM KLA2139 SMDI06 A003 145062UM A003_145062UM 2026-09-05 16:10
SMDI06-A003_1565PAD3 KLA2139 SMDI06 A003 1565PAD3 A003_1565PAD3 2026-09-05 16:10
SMDI06-A003_3365GATE KLA2139 SMDI06 A003 3365GATE A003_3365GATE 2026-09-05 16:10
SMDI06-A003_5085COSI KLA2139 SMDI06 A003 5085COSI A003_5085COSI 2026-09-05 16:10

In [ ]:
"/" + (DATA_BASE_DIR / equip.name / "ins.dat").relative_to(DATA_BASE_DIR)

TypeError: can only concatenate str (not "WindowsPath") to str

In [37]:
for (rcp_key, device, layer, recipe, edit_time) in recipes:
    print(rcp_key, equip.model, equip.name, device, layer, recipe, edit_time)

SMDI06-A002_1565PAD3 KLA2139 SMDI06 A002 1565PAD3 A002_1565PAD3 2026-09-05 16:10
SMDI06-A003_118062UM KLA2139 SMDI06 A003 118062UM A003_118062UM 2026-09-05 16:10
SMDI06-A003_1400MOPT KLA2139 SMDI06 A003 1400MOPT A003_1400MOPT 2026-09-05 16:10
SMDI06-A003_145062UM KLA2139 SMDI06 A003 145062UM A003_145062UM 2026-09-05 16:10
SMDI06-A003_1565PAD3 KLA2139 SMDI06 A003 1565PAD3 A003_1565PAD3 2026-09-05 16:10
SMDI06-A003_3365GATE KLA2139 SMDI06 A003 3365GATE A003_3365GATE 2026-09-05 16:10
SMDI06-A003_5085COSI KLA2139 SMDI06 A003 5085COSI A003_5085COSI 2026-09-05 16:10
SMDI06-A003_537562UM KLA2139 SMDI06 A003 537562UM A003_537562UM 2026-09-05 16:10
SMDI06-A003_615562UM KLA2139 SMDI06 A003 615562UM A003_615562UM 2026-09-05 16:10
SMDI06-A003_616562UM KLA2139 SMDI06 A003 616562UM A003_616562UM 2026-09-05 16:10
SMDI06-A003_6600M2PT KLA2139 SMDI06 A003 6600M2PT A003_6600M2PT 2026-09-05 16:10
SMDI06-A003_665562UM KLA2139 SMDI06 A003 665562UM A003_665562UM 2026-09-05 16:10
SMDI06-A003_6900V2PT KLA2139 SMDI06 A003 6900V2PT A003_6900V2PT 2026-09-05 16:10
SMDI06-A003_715539UM KLA2139 SMDI06 A003 715539UM A003_715539UM 2026-09-05 16:10
SMDI06-A004_140062UM KLA2139 SMDI06 A004 140062UM A004_140062UM 2026-09-05 16:10
SMDI06-A004_1439TRET KLA2139 SMDI06 A004 1439TRET A004_1439TRET 2026-09-05 16:10
SMDI06-A004_145062UM KLA2139 SMDI06 A004 145062UM A004_145062UM 2026-09-05 16:10
SMDI06-A004_1565PAD3 KLA2139 SMDI06 A004 1565PAD3 A004_1565PAD3 2026-09-05 16:10
SMDI06-A004_168262UM KLA2139 SMDI06 A004 168262UM A004_168262UM 2026-09-05 16:10
SMDI06-A004_168862UM KLA2139 SMDI06 A004 168862UM A004_168862UM 2026-09-05 16:10
SMDI06-A004_169662UM KLA2139 SMDI06 A004 169662UM A004_169662UM 2026-09-05 16:10
SMDI06-A004_172062UM KLA2139 SMDI06 A004 172062UM A004_172062UM 2026-09-05 16:10
SMDI06-A004_174062UM KLA2139 SMDI06 A004 174062UM A004_174062UM 2026-09-05 16:10
SMDI06-A004_3300GTPT KLA2139 SMDI06 A004 3300GTPT A004_3300GTPT 2026-09-05 16:10
SMDI06-A004_3365GATE KLA2139 SMDI06 A004 3365GATE A004_3365GATE 2026-09-05 16:10
SMDI06-A004_357862UM KLA2139 SMDI06 A004 357862UM A004_357862UM 2026-09-05 16:10
SMDI06-A004_5085COSI KLA2139 SMDI06 A004 5085COSI A004_5085COSI 2026-09-05 16:10
SMDI06-A004_610062UM KLA2139 SMDI06 A004 610062UM A004_610062UM 2026-09-05 16:10
SMDI06-A004_615562UM KLA2139 SMDI06 A004 615562UM A004_615562UM 2026-09-05 16:10
SMDI06-A004_665562UM KLA2139 SMDI06 A004 665562UM A004_665562UM 2026-09-05 16:10
SMDI06-A004_715539UM KLA2139 SMDI06 A004 715539UM A004_715539UM 2026-09-05 16:10
SMDI06-A101_1439TRET KLA2139 SMDI06 A101 1439TRET A101_1439TRET 2026-09-05 16:10
SMDI06-A101_152062UM KLA2139 SMDI06 A101 152062UM A101_152062UM 2026-09-05 16:10
SMDI06-A101_5800CTPT KLA2139 SMDI06 A101 5800CTPT A101_5800CTPT 2026-09-05 16:10
SMDI06-A101_6600M2PT KLA2139 SMDI06 A101 6600M2PT A101_6600M2PT 2026-09-05 16:10
SMDI06-A101_6655M2ET KLA2139 SMDI06 A101 6655M2ET A101_6655M2ET 2026-09-05 16:10
SMDI06-A102_138062UM KLA2139 SMDI06 A102 138062UM A102_138062UM 2026-09-05 16:10
SMDI06-A102_1400MOPT KLA2139 SMDI06 A102 1400MOPT A102_1400MOPT 2026-09-05 16:10
SMDI06-A102_1439TRET KLA2139 SMDI06 A102 1439TRET A102_1439TRET 2026-09-05 16:10
SMDI06-A102_1565PAD3 KLA2139 SMDI06 A102 1565PAD3 A102_1565PAD3 2026-09-05 16:10
SMDI06-A102_3300GTPT KLA2139 SMDI06 A102 3300GTPT A102_3300GTPT 2026-09-05 16:10
SMDI06-A102_3365GATE KLA2139 SMDI06 A102 3365GATE A102_3365GATE 2026-09-05 16:10
SMDI06-A102_4580SWET KLA2139 SMDI06 A102 4580SWET A102_4580SWET 2026-09-05 16:10
SMDI06-A102_4870SBPT KLA2139 SMDI06 A102 4870SBPT A102_4870SBPT 2026-09-05 16:10
SMDI06-A102_5085COSI KLA2139 SMDI06 A102 5085COSI A102_5085COSI 2026-09-05 16:10
SMDI06-A102_615562UM KLA2139 SMDI06 A102 615562UM A102_615562UM 2026-09-05 16:10
SMDI06-A102_6600M2PT KLA2139 SMDI06 A102 6600M2PT A102_6600M2PT 2026-09-05 16:10
SMDI06-A102_6655M2ET KLA2139 SMDI06 A102 6655M2ET A102_6655M2ET 2026-09-05 16:10
SMDI06-A103_1439TRET KLA2139 SMDI06 A103 1439TRET A103_1439TRET 2026-09-05 16:10
SMDI06-A103_1565PAD3 KLA2139 SMDI06 A103 1565PAD3 A103_1565PAD3 2026-09-05 16:10
SMDI06-A103_3300GTPT KLA2139 SMDI06 A103 3300GTPT A103_3300GTPT 2026-09-05 16:10
SMDI06-A103_3365GATE KLA2139 SMDI06 A103 3365GATE A103_3365GATE 2026-09-05 16:10
SMDI06-A103_366062UM KLA2139 SMDI06 A103 366062UM A103_366062UM 2026-09-05 16:10
SMDI06-A103_460062UM KLA2139 SMDI06 A103 460062UM A103_460062UM 2026-09-05 16:10
SMDI06-A103_5085COSI KLA2139 SMDI06 A103 5085COSI A103_5085COSI 2026-09-05 16:10
SMDI06-A103_5800CTPT KLA2139 SMDI06 A103 5800CTPT A103_5800CTPT 2026-09-05 16:10
SMDI06-A103_615562UM KLA2139 SMDI06 A103 615562UM A103_615562UM 2026-09-05 16:10
SMDI06-A103_6400V1PT KLA2139 SMDI06 A103 6400V1PT A103_6400V1PT 2026-09-05 16:10
SMDI06-A103_6465125U KLA2139 SMDI06 A103 6465125U A103_6465125U 2026-09-05 16:10
SMDI06-A103_6655M2ET KLA2139 SMDI06 A103 6655M2ET A103_6655M2ET 2026-09-05 16:10
SMDI06-A103_880062UM KLA2139 SMDI06 A103 880062UM A103_880062UM 2026-09-05 16:10
SMDI06-A103_9200POPT KLA2139 SMDI06 A103 9200POPT A103_9200POPT 2026-09-05 16:10
SMDI06-A104_1439TRET KLA2139 SMDI06 A104 1439TRET A104_1439TRET 2026-09-17 12:29
SMDI06-A104_615562UM KLA2139 SMDI06 A104 615562UM A104_615562UM 2026-10-09 09:10
SMDI06-A202_3495NSRC KLA2139 SMDI06 A202 3495NSRC A202_3495NSRC 2026-09-05 16:10
SMDI06-A301_3365GATE KLA2139 SMDI06 A301 3365GATE A301_3365GATE 2026-09-05 16:10
SMDI06-A301_3495NSRC KLA2139 SMDI06 A301 3495NSRC A301_3495NSRC 2026-09-05 16:10
SMDI06-A601_1400MASK KLA2139 SMDI06 A601 1400MASK A601_1400MASK 2026-09-05 16:10
SMDI06-A601_1439TRET KLA2139 SMDI06 A601 1439TRET A601_1439TRET 2026-09-05 16:10
SMDI06-A601_145062UM KLA2139 SMDI06 A601 145062UM A601_145062UM 2026-09-05 16:10
SMDI06-A601_3365GATE KLA2139 SMDI06 A601 3365GATE A601_3365GATE 2026-09-05 16:10
SMDI06-A601_5085COSI KLA2139 SMDI06 A601 5085COSI A601_5085COSI 2026-09-05 16:10
SMDI06-A601_6100M1PT KLA2139 SMDI06 A601 6100M1PT A601_6100M1PT 2026-09-05 16:10
SMDI06-A601_615562UM KLA2139 SMDI06 A601 615562UM A601_615562UM 2026-09-05 16:10
SMDI06-A601_715539UM KLA2139 SMDI06 A601 715539UM A601_715539UM 2026-09-05 16:10
SMDI06-A601_765539UM KLA2139 SMDI06 A601 765539UM A601_765539UM 2026-09-05 16:10
SMDI06-A603_1565PAD3 KLA2139 SMDI06 A603 1565PAD3 A603_1565PAD3 2026-09-05 16:10
SMDI06-A604_1439TRET KLA2139 SMDI06 A604 1439TRET A604_1439TRET 2026-09-05 16:10
SMDI06-A604_1565PAD3 KLA2139 SMDI06 A604 1565PAD3 A604_1565PAD3 2026-09-05 16:10
SMDI06-A604_516062UM KLA2139 SMDI06 A604 516062UM A604_516062UM 2026-09-05 16:10
SMDI06-A604_615562UM KLA2139 SMDI06 A604 615562UM A604_615562UM 2026-09-05 16:10
SMDI06-A604_715539UM KLA2139 SMDI06 A604 715539UM A604_715539UM 2026-09-05 16:10
SMDI06-A604_7655M4ET KLA2139 SMDI06 A604 7655M4ET A604_7655M4ET 2026-09-05 16:10
SMDI06-A605_1565PAD3 KLA2139 SMDI06 A605 1565PAD3 A605_1565PAD3 2026-09-05 16:10
SMDI06-A605_665562UM KLA2139 SMDI06 A605 665562UM A605_665562UM 2026-09-05 16:10
SMDI06-A607_056562UM KLA2139 SMDI06 A607 056562UM A607_056562UM 2026-09-05 16:10
SMDI06-A607_1439TRET KLA2139 SMDI06 A607 1439TRET A607_1439TRET 2026-09-05 16:10
SMDI06-A607_3300MASK KLA2139 SMDI06 A607 3300MASK A607_3300MASK 2026-09-05 16:10
SMDI06-A607_5085COSI KLA2139 SMDI06 A607 5085COSI A607_5085COSI 2026-09-05 16:10
SMDI06-A607_615562UM KLA2139 SMDI06 A607 615562UM A607_615562UM 2026-09-05 16:10
SMDI06-A607_715539UM KLA2139 SMDI06 A607 715539UM A607_715539UM 2026-09-05 16:10
SMDI06-A607_8155M5ET KLA2139 SMDI06 A607 8155M5ET A607_8155M5ET 2026-09-05 16:10
SMDI06-A609_170062UM KLA2139 SMDI06 A609 170062UM A609_170062UM 2026-10-12 19:59
SMDI06-A609_3300MASK KLA2139 SMDI06 A609 3300MASK A609_3300MASK 2026-09-21 20:38
SMDI06-A609_3365GATE KLA2139 SMDI06 A609 3365GATE A609_3365GATE 2026-09-05 16:10
SMDI06-A609_4870SBPT KLA2139 SMDI06 A609 4870SBPT A609_4870SBPT 2026-09-05 16:10
SMDI06-A609_5085COSI KLA2139 SMDI06 A609 5085COSI A609_5085COSI 2026-09-05 16:10
SMDI06-A609_615562UM KLA2139 SMDI06 A609 615562UM A609_615562UM 2026-09-05 16:10
SMDI06-A609_665562UM KLA2139 SMDI06 A609 665562UM A609_665562UM 2026-09-05 16:10
SMDI06-A610_1565PAD3 KLA2139 SMDI06 A610 1565PAD3 A610_1565PAD3 2026-09-05 16:10
SMDI06-A612_1565PAD3 KLA2139 SMDI06 A612 1565PAD3 A612_1565PAD3 2026-09-05 16:10
SMDI06-A612_537562UM KLA2139 SMDI06 A612 537562UM A612_537562UM 2026-09-05 16:10
SMDI06-A613_1565PAD3 KLA2139 SMDI06 A613 1565PAD3 A613_1565PAD3 2026-09-05 16:10
SMDI06-A614_1565PAD3 KLA2139 SMDI06 A614 1565PAD3 A614_1565PAD3 2026-09-05 16:10
SMDI06-A614_5800CTPT KLA2139 SMDI06 A614 5800CTPT A614_5800CTPT 2026-09-05 16:10
SMDI06-A618_1565PAD3 KLA2139 SMDI06 A618 1565PAD3 A618_1565PAD3 2026-09-18 22:38
SMDI06-A802_1565PAD3 KLA2139 SMDI06 A802 1565PAD3 A802_1565PAD3 2026-09-05 16:10
SMDI06-A802_586562UM KLA2139 SMDI06 A802 586562UM A802_586562UM 2026-09-05 16:10
SMDI06-A803_1565PAD3 KLA2139 SMDI06 A803 1565PAD3 A803_1565PAD3 2026-09-05 16:10
SMDI06-A804_1439TRET KLA2139 SMDI06 A804 1439TRET A804_1439TRET 2026-09-05 16:10
SMDI06-A804_1565PAD3 KLA2139 SMDI06 A804 1565PAD3 A804_1565PAD3 2026-09-05 16:10
SMDI06-A804_225039F0 KLA2139 SMDI06 A804 225039F0 A804_225039F0 2026-09-05 16:10
SMDI06-A804_3365GATE KLA2139 SMDI06 A804 3365GATE A804_3365GATE 2026-09-05 16:10
SMDI06-A804_615562UM KLA2139 SMDI06 A804 615562UM A804_615562UM 2026-09-05 16:10
SMDI06-A804_665562UM KLA2139 SMDI06 A804 665562UM A804_665562UM 2026-09-05 16:10
SMDI06-A804_7155M3ET KLA2139 SMDI06 A804 7155M3ET A804_7155M3ET 2026-09-05 16:10
SMDI06-A805_1565PAD3 KLA2139 SMDI06 A805 1565PAD3 A805_1565PAD3 2026-09-05 16:10
SMDI06-A806_1565PAD3 KLA2139 SMDI06 A806 1565PAD3 A806_1565PAD3 2026-09-05 16:10
SMDI06-A807_1565PAD3 KLA2139 SMDI06 A807 1565PAD3 A807_1565PAD3 2026-09-05 16:10
SMDI06-A903_3495NSRC KLA2139 SMDI06 A903 3495NSRC A903_3495NSRC 2026-09-05 16:10
SMDI06-A904_3365GATE KLA2139 SMDI06 A904 3365GATE A904_3365GATE 2026-09-05 16:10
SMDI06-AB17_615562UM KLA2139 SMDI06 AB17 615562UM AB17_615562UM 2026-09-05 16:10
SMDI06-AB17_7155M3ET KLA2139 SMDI06 AB17 7155M3ET AB17_7155M3ET 2026-09-05 16:10
SMDI06-AB19_7155M3ET KLA2139 SMDI06 AB19 7155M3ET AB19_7155M3ET 2026-09-05 16:10
SMDI06-AB20_1565PAD3 KLA2139 SMDI06 AB20 1565PAD3 AB20_1565PAD3 2026-09-05 16:10
SMDI06-AB20_7655M4ET KLA2139 SMDI06 AB20 7655M4ET AB20_7655M4ET 2026-09-05 16:10
SMDI06-AB21_602562UM KLA2139 SMDI06 AB21 602562UM AB21_602562UM 2026-09-05 16:10
SMDI06-AG14_1400MOPT KLA2139 SMDI06 AG14 1400MOPT AG14_1400MOPT 2026-09-05 16:10
SMDI06-AG14_1439TRET KLA2139 SMDI06 AG14 1439TRET AG14_1439TRET 2026-09-05 16:10
SMDI06-AG14_145062UM KLA2139 SMDI06 AG14 145062UM AG14_145062UM 2026-09-05 16:10
SMDI06-AG14_146262UM KLA2139 SMDI06 AG14 146262UM AG14_146262UM 2026-09-05 16:10
SMDI06-AG14_224562UM KLA2139 SMDI06 AG14 224562UM AG14_224562UM 2026-09-05 16:10
SMDI06-AG14_3365GATE KLA2139 SMDI06 AG14 3365GATE AG14_3365GATE 2026-09-05 16:10
SMDI06-AG14_366062UM KLA2139 SMDI06 AG14 366062UM AG14_366062UM 2026-09-05 16:10
SMDI06-AG14_4580SWET KLA2139 SMDI06 AG14 4580SWET AG14_4580SWET 2026-09-05 16:10
SMDI06-AG14_480062UM KLA2139 SMDI06 AG14 480062UM AG14_480062UM 2026-09-05 16:10
SMDI06-AG14_485062UM KLA2139 SMDI06 AG14 485062UM AG14_485062UM 2026-09-05 16:10
SMDI06-AG14_486562UM KLA2139 SMDI06 AG14 486562UM AG14_486562UM 2026-09-05 16:10
SMDI06-AG14_4870SBPT KLA2139 SMDI06 AG14 4870SBPT AG14_4870SBPT 2026-09-05 16:10
SMDI06-AG14_5085COSI KLA2139 SMDI06 AG14 5085COSI AG14_5085COSI 2026-09-05 16:10
SMDI06-AG14_537562UM KLA2139 SMDI06 AG14 537562UM AG14_537562UM 2026-09-05 16:10
SMDI06-AG14_586562UM KLA2139 SMDI06 AG14 586562UM AG14_586562UM 2026-09-05 16:10
SMDI06-AG14_616562UM KLA2139 SMDI06 AG14 616562UM AG14_616562UM 2026-09-05 16:10
SMDI06-AG14_652562UM KLA2139 SMDI06 AG14 652562UM AG14_652562UM 2026-09-05 16:10
SMDI06-AG14_665562UM KLA2139 SMDI06 AG14 665562UM AG14_665562UM 2026-09-05 16:10
SMDI06-AG14_666562UM KLA2139 SMDI06 AG14 666562UM AG14_666562UM 2026-09-05 16:10
SMDI06-AG14_686562UM KLA2139 SMDI06 AG14 686562UM AG14_686562UM 2026-09-05 16:10
SMDI06-AG14_6900V2PT KLA2139 SMDI06 AG14 6900V2PT AG14_6900V2PT 2026-09-05 16:10
SMDI06-AG14_7155M3ET KLA2139 SMDI06 AG14 7155M3ET AG14_7155M3ET 2026-09-05 16:10
SMDI06-AG14_880062UM KLA2139 SMDI06 AG14 880062UM AG14_880062UM 2026-09-05 16:10
SMDI06-AG15_006162UM KLA2139 SMDI06 AG15 006162UM AG15_006162UM 2026-09-05 16:10
SMDI06-AG15_052262UM KLA2139 SMDI06 AG15 052262UM AG15_052262UM 2026-09-05 16:10
SMDI06-AG15_144062UM KLA2139 SMDI06 AG15 144062UM AG15_144062UM 2026-09-05 16:10
SMDI06-AG15_161062UM KLA2139 SMDI06 AG15 161062UM AG15_161062UM 2026-09-05 16:10
SMDI06-AG15_162062UM KLA2139 SMDI06 AG15 162062UM AG15_162062UM 2026-09-05 16:10
SMDI06-AG15_176262UM KLA2139 SMDI06 AG15 176262UM AG15_176262UM 2026-09-05 16:10
SMDI06-AG15_179162UM KLA2139 SMDI06 AG15 179162UM AG15_179162UM 2026-09-05 16:10
SMDI06-AG15_3300GTPT KLA2139 SMDI06 AG15 3300GTPT AG15_3300GTPT 2026-09-05 16:10
SMDI06-AG15_3300MASK KLA2139 SMDI06 AG15 3300MASK AG15_3300MASK 2026-09-05 16:10
SMDI06-AG15_465062UM KLA2139 SMDI06 AG15 465062UM AG15_465062UM 2026-09-05 16:10
SMDI06-AG15_480062UM KLA2139 SMDI06 AG15 480062UM AG15_480062UM 2026-09-05 16:10
SMDI06-AG15_485062UM KLA2139 SMDI06 AG15 485062UM AG15_485062UM 2026-09-05 16:10
SMDI06-AG15_485362UM KLA2139 SMDI06 AG15 485362UM AG15_485362UM 2026-09-05 16:10
SMDI06-AG15_5085COSI KLA2139 SMDI06 AG15 5085COSI AG15_5085COSI 2026-09-05 16:10
SMDI06-AG15_513062UM KLA2139 SMDI06 AG15 513062UM AG15_513062UM 2026-09-05 16:10
SMDI06-AG15_537562UM KLA2139 SMDI06 AG15 537562UM AG15_537562UM 2026-09-05 16:10
SMDI06-AG15_5800CTPT KLA2139 SMDI06 AG15 5800CTPT AG15_5800CTPT 2026-09-05 16:10
SMDI06-AG15_6100M1PT KLA2139 SMDI06 AG15 6100M1PT AG15_6100M1PT 2026-09-05 16:10
SMDI06-AG15_6900V2PT KLA2139 SMDI06 AG15 6900V2PT AG15_6900V2PT 2026-09-05 16:10
SMDI06-AG15_913062UM KLA2139 SMDI06 AG15 913062UM AG15_913062UM 2026-09-05 16:10
SMDI06-AG15_9200POPT KLA2139 SMDI06 AG15 9200POPT AG15_9200POPT 2026-09-05 16:10
SMDI06-AG17_1400MOPT KLA2139 SMDI06 AG17 1400MOPT AG17_1400MOPT 2026-09-05 16:10
SMDI06-AG17_216062UM KLA2139 SMDI06 AG17 216062UM AG17_216062UM 2026-09-05 16:10
SMDI06-AG17_287562UM KLA2139 SMDI06 AG17 287562UM AG17_287562UM 2026-09-05 16:10
SMDI06-AG17_5905125U KLA2139 SMDI06 AG17 5905125U AG17_5905125U 2026-09-05 16:10
SMDI06-AG17_6100M1PT KLA2139 SMDI06 AG17 6100M1PT AG17_6100M1PT 2026-09-05 16:10
SMDI06-AG17_6100MASK KLA2139 SMDI06 AG17 6100MASK AG17_6100MASK 2026-09-05 16:10
SMDI06-AG17_615539UM KLA2139 SMDI06 AG17 615539UM AG17_615539UM 2026-09-05 16:10
SMDI06-AG17_694562UM KLA2139 SMDI06 AG17 694562UM AG17_694562UM 2026-09-05 16:10
SMDI06-AG18_1400MASK KLA2139 SMDI06 AG18 1400MASK AG18_1400MASK 2026-09-05 16:10
SMDI06-AG18_1400MOPT KLA2139 SMDI06 AG18 1400MOPT AG18_1400MOPT 2026-09-05 16:10
SMDI06-AG18_1439TRET KLA2139 SMDI06 AG18 1439TRET AG18_1439TRET 2026-09-05 16:10
SMDI06-AG18_145062UM KLA2139 SMDI06 AG18 145062UM AG18_145062UM 2026-09-05 16:10
SMDI06-AG18_189462UM KLA2139 SMDI06 AG18 189462UM AG18_189462UM 2026-09-05 16:10
SMDI06-AG18_205062UM KLA2139 SMDI06 AG18 205062UM AG18_205062UM 2026-09-05 16:10
SMDI06-AG18_3300GTPT KLA2139 SMDI06 AG18 3300GTPT AG18_3300GTPT 2026-09-05 16:10
SMDI06-AG18_3365GATE KLA2139 SMDI06 AG18 3365GATE AG18_3365GATE 2026-09-05 16:10
SMDI06-AG18_5085COSI KLA2139 SMDI06 AG18 5085COSI AG18_5085COSI 2026-09-05 16:10
SMDI06-AG18_660062UM KLA2139 SMDI06 AG18 660062UM AG18_660062UM 2026-09-05 16:10
SMDI06-AG18_665562UM KLA2139 SMDI06 AG18 665562UM AG18_665562UM 2026-09-05 16:10
SMDI06-AG18_686562UM KLA2139 SMDI06 AG18 686562UM AG18_686562UM 2026-09-05 16:10
SMDI06-AG18_702562UM KLA2139 SMDI06 AG18 702562UM AG18_702562UM 2026-09-05 16:10
SMDI06-AG18_744562UM KLA2139 SMDI06 AG18 744562UM AG18_744562UM 2026-09-05 16:10
SMDI06-AG18_7655M4ET KLA2139 SMDI06 AG18 7655M4ET AG18_7655M4ET 2026-09-05 16:10
SMDI06-AG19_1400MOPT KLA2139 SMDI06 AG19 1400MOPT AG19_1400MOPT 2026-09-05 16:10
SMDI06-AG19_1439TRET KLA2139 SMDI06 AG19 1439TRET AG19_1439TRET 2026-09-05 16:10
SMDI06-AG19_145062UM KLA2139 SMDI06 AG19 145062UM AG19_145062UM 2026-09-05 16:10
SMDI06-AG19_1565PAD3 KLA2139 SMDI06 AG19 1565PAD3 AG19_1565PAD3 2026-09-05 16:10
SMDI06-AG19_172062UM KLA2139 SMDI06 AG19 172062UM AG19_172062UM 2026-09-05 16:10
SMDI06-AG19_174062UM KLA2139 SMDI06 AG19 174062UM AG19_174062UM 2026-09-05 16:10
SMDI06-AG19_3365GATE KLA2139 SMDI06 AG19 3365GATE AG19_3365GATE 2026-09-05 16:10
SMDI06-AG19_357462UM KLA2139 SMDI06 AG19 357462UM AG19_357462UM 2026-09-05 16:10
SMDI06-AG19_365062UM KLA2139 SMDI06 AG19 365062UM AG19_365062UM 2026-09-05 16:10
SMDI06-AG19_366462UM KLA2139 SMDI06 AG19 366462UM AG19_366462UM 2026-09-05 16:10
SMDI06-AG19_4580SWET KLA2139 SMDI06 AG19 4580SWET AG19_4580SWET 2026-09-20 12:00
SMDI06-AG19_5085COSI KLA2139 SMDI06 AG19 5085COSI AG19_5085COSI 2026-09-20 12:18
SMDI06-AG19_580039UM KLA2139 SMDI06 AG19 580039UM AG19_580039UM 2026-09-05 16:10
SMDI06-AG19_5905125U KLA2139 SMDI06 AG19 5905125U AG19_5905125U 2026-09-05 16:10
SMDI06-AG19_6100M1PT KLA2139 SMDI06 AG19 6100M1PT AG19_6100M1PT 2026-09-05 16:10
SMDI06-AG19_665562UM KLA2139 SMDI06 AG19 665562UM AG19_665562UM 2026-09-28 20:47
SMDI06-AG19_6965125U KLA2139 SMDI06 AG19 6965125U AG19_6965125U 2026-09-05 16:10
SMDI06-AG19_7655M4ET KLA2139 SMDI06 AG19 7655M4ET AG19_7655M4ET 2026-09-05 16:10
SMDI06-AG19_9260POET KLA2139 SMDI06 AG19 9260POET AG19_9260POET 2026-09-05 16:10
SMDI06-AG20_1400MOPT KLA2139 SMDI06 AG20 1400MOPT AG20_1400MOPT 2026-09-05 16:10
SMDI06-AG20_1439TRET KLA2139 SMDI06 AG20 1439TRET AG20_1439TRET 2026-09-05 16:10
SMDI06-AG20_145062UM KLA2139 SMDI06 AG20 145062UM AG20_145062UM 2026-09-05 16:10
SMDI06-AG20_173062UM KLA2139 SMDI06 AG20 173062UM AG20_173062UM 2026-09-05 16:10
SMDI06-AG20_174062UM KLA2139 SMDI06 AG20 174062UM AG20_174062UM 2026-09-05 16:10
SMDI06-AG20_175562UM KLA2139 SMDI06 AG20 175562UM AG20_175562UM 2026-09-05 16:10
SMDI06-AG20_216062UM KLA2139 SMDI06 AG20 216062UM AG20_216062UM 2026-09-05 16:10
SMDI06-AG20_355439UM KLA2139 SMDI06 AG20 355439UM AG20_355439UM 2026-09-05 16:10
SMDI06-AG20_355462UM KLA2139 SMDI06 AG20 355462UM AG20_355462UM 2026-09-05 16:10
SMDI06-AG20_357462UM KLA2139 SMDI06 AG20 357462UM AG20_357462UM 2026-09-05 16:10
SMDI06-AG20_458062UM KLA2139 SMDI06 AG20 458062UM AG20_458062UM 2026-09-05 16:10
SMDI06-AG20_4580SWET KLA2139 SMDI06 AG20 4580SWET AG20_4580SWET 2026-09-05 16:10
SMDI06-AG20_465062UM KLA2139 SMDI06 AG20 465062UM AG20_465062UM 2026-09-05 16:10
SMDI06-AG20_6465125U KLA2139 SMDI06 AG20 6465125U AG20_6465125U 2026-09-05 16:10
SMDI06-AG20_7100M3PT KLA2139 SMDI06 AG20 7100M3PT AG20_7100M3PT 2026-09-05 16:10
SMDI06-AG20_715539UM KLA2139 SMDI06 AG20 715539UM AG20_715539UM 2026-09-05 16:10
SMDI06-AG20_7600M4PT KLA2139 SMDI06 AG20 7600M4PT AG20_7600M4PT 2026-09-05 16:10
SMDI06-AG20_920062UM KLA2139 SMDI06 AG20 920062UM AG20_920062UM 2026-09-05 16:10
SMDI06-AG20_926062UM KLA2139 SMDI06 AG20 926062UM AG20_926062UM 2026-09-05 16:10
SMDI06-AG21_035562UM KLA2139 SMDI06 AG21 035562UM AG21_035562UM 2026-09-05 16:10
SMDI06-AG21_1400MOPT KLA2139 SMDI06 AG21 1400MOPT AG21_1400MOPT 2026-09-05 16:10
SMDI06-AG21_1439TRET KLA2139 SMDI06 AG21 1439TRET AG21_1439TRET 2026-09-05 16:10
SMDI06-AG21_1565PAD3 KLA2139 SMDI06 AG21 1565PAD3 AG21_1565PAD3 2026-09-05 16:10
SMDI06-AG21_171862UM KLA2139 SMDI06 AG21 171862UM AG21_171862UM 2026-09-05 16:10
SMDI06-AG21_175562UM KLA2139 SMDI06 AG21 175562UM AG21_175562UM 2026-09-05 16:10
SMDI06-AG21_195062UM KLA2139 SMDI06 AG21 195062UM AG21_195062UM 2026-09-05 16:10
SMDI06-AG21_3365GATE KLA2139 SMDI06 AG21 3365GATE AG21_3365GATE 2026-09-05 16:10
SMDI06-AG21_339062UM KLA2139 SMDI06 AG21 339062UM AG21_339062UM 2026-09-05 16:10
SMDI06-AG21_366462UM KLA2139 SMDI06 AG21 366462UM AG21_366462UM 2026-09-05 16:10
SMDI06-AG21_465062UM KLA2139 SMDI06 AG21 465062UM AG21_465062UM 2026-09-05 16:10
SMDI06-AG21_480062UM KLA2139 SMDI06 AG21 480062UM AG21_480062UM 2026-09-05 16:10
SMDI06-AG21_486562UM KLA2139 SMDI06 AG21 486562UM AG21_486562UM 2026-09-05 16:10
SMDI06-AG21_497262UM KLA2139 SMDI06 AG21 497262UM AG21_497262UM 2026-09-05 16:10

In [39]:
df_equip_db

Empty DataFrame
Columns: [recipe_key, dt_edit_time, device, layer, recipe, backup_file_path]
Index: []